name: sirama
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  http: ^1.1.0
  in_app_update: ^4.2.2
  json_annotation: ^4.8.1
  m_widget:
    git:
      url: https://github.com/BlastTea/MWidget.git
      ref: 38e64ee8e33e19ccfdd7ffa712eced4a3ed5fe6c
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  

flutter:
  uses-material-design: true
  fonts:
  - family: PlusJakartaSans
    fonts:
      - asset: fonts/PlusJakartaSans.ttf
  assets:
    - assets/
    - assets/icons/
      # - asset: fonts/static/PlusJakartaSans-Bold.ttf
      # - asset: fonts/static/PlusJakartaSans-BoldItalic.ttf
      #   style: italic
      # - asset: fonts/static/PlusJakartaSans-ExtraBold.ttf
      # - asset: fonts/static/PlusJakartaSans-ExtraBoldItalic.ttf
      #   style: italic
      # - asset: fonts/static/PlusJakartaSans-ExtraItalic.ttf
      #   style: italic
      # - asset: fonts/static/PlusJakartaSans-ExtraLightItalic.ttf
      #   style: italic
      # - asset: fonts/static/PlusJakartaSans-Italic.ttf
      #   style: italic
      # - asset: fonts/static/PlusJakartaSans-Light.ttf
      # - asset: fonts/static/PlusJakartaSans-LightItalic.ttf
      #   style: italic
      # - asset: fonts/static/PlusJakartaSans-Medium.ttf
      # - asset: fonts/static/PlusJakartaSans-MediumItalic.ttf
      #   style: italic
      # - asset: fonts/static/PlusJakartaSans-SemiBold.ttf
      # - asset: fonts/static/PlusJakartaSans-SemiBoldItalic.ttf
      #   style: italic

  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/dummy logo.png"