name: sirama
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0-alpha.2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_html: ^3.0.0-beta.2
  flutter_native_splash: ^2.3.9
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  m_widget:
    git:
      url: https://github.com/BlastTea/MWidget.git
      ref: 63f3535f21421dad4f8ebc94b7545ed4aa255dd8
  pod_player: ^0.2.1
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/svgs/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Logo SIRAMA.png"

flutter_native_splash:
  color: '#FFFFFF'
  image: assets/Logo SIRAMA.png
  android_12:
    image: assets/Logo SIRAMA.png
    color: '#FFFFFF'
  web: false
