name: sirama
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  in_app_update: ^4.2.2
  json_annotation: ^4.8.1
  m_widget:
    git:
      url: https://github.com/BlastTea/MWidget.git
      ref: 7ab7b7d943f4f1479a0941cbe1fdfee24ee91df2
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
