import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:m_widget/m_widget.dart';
import 'package:sirama/blocs/blocs.dart';
import 'package:sirama/main.dart';
import 'package:sirama/models/models.dart';
import 'package:sirama/services/services.dart';
import 'package:sirama/utils/utils.dart';
import 'package:sirama/views/pages/pages.dart';
import 'package:sirama/views/widgets/widgets.dart';
import 'package:intl/intl.dart';
import 'package:carousel_slider/carousel_slider.dart';

part 'home_fragment.dart';
part 'content_fragment.dart';
part 'profile_fragment.dart';
part 'chat_fragment.dart';
part 'ask_the_expert_fragment.dart';
